// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxgS6ernmSstPyH6iFQYXs3HvvvqNIksI',
    appId: '1:321100878555:web:864b3c6b373b45a2f1b2fe',
    messagingSenderId: '321100878555',
    projectId: 'groupfirebase-62f66',
    authDomain: 'groupfirebase-62f66.firebaseapp.com',
    storageBucket: 'groupfirebase-62f66.appspot.com',
    measurementId: 'G-8C5DNR2J92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2IHitiBEpvv_ug8dgrEe-JQiN64WTkh8',
    appId: '1:321100878555:android:7f27564601b4e4fff1b2fe',
    messagingSenderId: '321100878555',
    projectId: 'groupfirebase-62f66',
    storageBucket: 'groupfirebase-62f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3UhbcvkZyoOqqXjUmkgvxccjZFnRAjOs',
    appId: '1:321100878555:ios:c857939a5c5768b5f1b2fe',
    messagingSenderId: '321100878555',
    projectId: 'groupfirebase-62f66',
    storageBucket: 'groupfirebase-62f66.appspot.com',
    iosBundleId: 'com.example.groupchatfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3UhbcvkZyoOqqXjUmkgvxccjZFnRAjOs',
    appId: '1:321100878555:ios:c857939a5c5768b5f1b2fe',
    messagingSenderId: '321100878555',
    projectId: 'groupfirebase-62f66',
    storageBucket: 'groupfirebase-62f66.appspot.com',
    iosBundleId: 'com.example.groupchatfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxgS6ernmSstPyH6iFQYXs3HvvvqNIksI',
    appId: '1:321100878555:web:805f1a41de987e58f1b2fe',
    messagingSenderId: '321100878555',
    projectId: 'groupfirebase-62f66',
    authDomain: 'groupfirebase-62f66.firebaseapp.com',
    storageBucket: 'groupfirebase-62f66.appspot.com',
    measurementId: 'G-546HXDE7RY',
  );

}